/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mikrozirkmixer1.pkg0;

import FreqAnalyzer.Globals;
import java.awt.event.ActionEvent;
import javax.swing.JFileChooser;

/**
 *
 * @author eckerts
 */
public class FileOpenDialog extends javax.swing.JDialog {

    /**
     * Creates new form FileOpenDialog
     */
    public FileOpenDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initMyThings();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        outliersButtonGroup = new javax.swing.ButtonGroup();
        fileLabel = new javax.swing.JLabel();
        fileTextField = new javax.swing.JTextField();
        fileButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        samplingRateLabel = new javax.swing.JLabel();
        samplingRateTextField = new javax.swing.JTextField();
        biasCheckbox = new javax.swing.JCheckBox();
        zoomLabel1 = new javax.swing.JLabel();
        zoomTextField = new javax.swing.JTextField();
        zoomLabel2 = new javax.swing.JLabel();
        normalizationCheckbox = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        outliers_upper_bound_textfield = new javax.swing.JTextField();
        outliers_tolerance_TextField = new javax.swing.JTextField();
        outliers_auto_radiobutton = new javax.swing.JRadioButton();
        outliersToleranceLabel = new javax.swing.JLabel();
        outliers_upper_bound_label = new javax.swing.JLabel();
        outliers_off_radiobutton = new javax.swing.JRadioButton();
        outliers_lower_bound_label = new javax.swing.JLabel();
        outliers_lower_bound_textfield = new javax.swing.JTextField();
        outliers_manually_radiobutton = new javax.swing.JRadioButton();
        replace_outliers_title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Open Data Textfile");

        fileLabel.setText("Get data from text file: ");
        fileLabel.setToolTipText("Text files have extension \".txt\"");

        fileTextField.setToolTipText("");

        fileButton.setText("...");
        fileButton.setToolTipText("browse your files");
        fileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileButtonActionPerformed(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        samplingRateLabel.setText("Sampling rate of Data in 1/s");

        samplingRateTextField.setText("100");
        samplingRateTextField.setToolTipText("");

        biasCheckbox.setText("remove Bias from Data");
        biasCheckbox.setToolTipText("the \"wave\" is pulled down to the x-axis and      * the fast fourrier algorithm performs better.");

        zoomLabel1.setText("Zoom Transformed Data to ");

        zoomTextField.setText("1");

        zoomLabel2.setText("% of full Range");

        normalizationCheckbox.setText("normalize values");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        outliers_upper_bound_textfield.setText("100");
        outliers_upper_bound_textfield.setEnabled(false);

        outliers_tolerance_TextField.setText("2");
        outliers_tolerance_TextField.setToolTipText("Tolerance for outliers: data which lies less than n times the standard deviation from the mean is accepted");

        outliers_auto_radiobutton.setText("automatically");
        outliers_auto_radiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outliers_auto_radiobuttonActionPerformed(evt);
            }
        });

        outliersToleranceLabel.setText("Tolerance: ");

        outliers_upper_bound_label.setText("upper bound");
        outliers_upper_bound_label.setEnabled(false);

        outliers_off_radiobutton.setText("Replace outliers off");
        outliers_off_radiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outliers_off_radiobuttonActionPerformed(evt);
            }
        });

        outliers_lower_bound_label.setText("lower bound");
        outliers_lower_bound_label.setEnabled(false);

        outliers_lower_bound_textfield.setText("0");
        outliers_lower_bound_textfield.setEnabled(false);

        outliers_manually_radiobutton.setText("manually");
        outliers_manually_radiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outliers_manually_radiobuttonActionPerformed(evt);
            }
        });

        replace_outliers_title.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        replace_outliers_title.setText("Replace outliers");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(outliers_auto_radiobutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(outliers_tolerance_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(outliers_off_radiobutton)
                    .addComponent(replace_outliers_title)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(outliers_manually_radiobutton)
                        .addGap(180, 180, 180)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(outliers_upper_bound_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(outliers_upper_bound_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(outliersToleranceLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(outliers_lower_bound_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(outliers_lower_bound_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(replace_outliers_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outliersToleranceLabel)
                    .addComponent(outliers_tolerance_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outliers_auto_radiobutton))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outliers_manually_radiobutton)
                    .addComponent(outliers_lower_bound_label)
                    .addComponent(outliers_lower_bound_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outliers_upper_bound_label)
                    .addComponent(outliers_upper_bound_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(outliers_off_radiobutton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(zoomLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(normalizationCheckbox)
                                .addGap(31, 31, 31))
                            .addComponent(biasCheckbox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zoomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zoomLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(okButton)
                                .addGap(18, 18, 18)
                                .addComponent(cancelButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fileLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fileButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(samplingRateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(samplingRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(samplingRateLabel)
                            .addComponent(samplingRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zoomLabel1)
                            .addComponent(zoomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zoomLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(biasCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(normalizationCheckbox)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fileButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void initMyThings(){
        outliersButtonGroup.add(outliers_auto_radiobutton);
        outliersButtonGroup.add(outliers_manually_radiobutton);
        outliersButtonGroup.add(outliers_off_radiobutton);
        outliersButtonGroup.setSelected(outliers_auto_radiobutton.getModel(), true);
        outliers_tolerance_TextField.setText(new Double(Globals.outliersTolerance).toString());
        outliers_lower_bound_textfield.setText(new Double(Globals.outliersLowerBound).toString());
        outliers_upper_bound_textfield.setText(new Double(Globals.outliersUpperBound).toString());
        fileTextField.setText(Globals.pathToDataFile);
        biasCheckbox.setSelected(Globals.removeBias);
        normalizationCheckbox.setSelected(Globals.normalization);
        zoomTextField.setText((new Double(Globals.freqDisplayTrimFactor*100)).toString());
        samplingRateTextField.setText(new Double(Globals.samplingRate).toString());
        this.
        fileButtonActionPerformed(new ActionEvent(this, 0, "First open"));
    }
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void fileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser(System.getProperty("user.dir"));
        if(Globals.lastFile != null) fileChooser.setCurrentDirectory(Globals.lastFile.getParentFile());
        fileChooser.setMultiSelectionEnabled(false);
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) 
            fileTextField.setText(fileChooser.getSelectedFile().getAbsolutePath());
            Globals.lastFile = fileChooser.getSelectedFile();
    }//GEN-LAST:event_fileButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        Globals.outliersTolerance = new Double(outliers_tolerance_TextField.getText()).doubleValue();
        Globals.outliersLowerBound = new Double(outliers_lower_bound_textfield.getText()).doubleValue();
        Globals.outliersUpperBound = new Double(outliers_upper_bound_textfield.getText()).doubleValue();
        Globals.pathToDataFile = fileTextField.getText();
        Globals.removeBias = biasCheckbox.isSelected();
        Globals.normalization = normalizationCheckbox.isSelected();
        Globals.freqDisplayTrimFactor = (new Double(zoomTextField.getText()).doubleValue())/100;
        Globals.samplingRate = new Double(samplingRateTextField.getText()).doubleValue();
        Globals.standardZoomFactorTransformed = 100 / new Double(zoomTextField.getText()).doubleValue();
        setVisible(false);
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void outliers_auto_radiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outliers_auto_radiobuttonActionPerformed
        outliers_tolerance_TextField.setEnabled(true);
        outliers_upper_bound_label.setEnabled(false);
        outliers_upper_bound_textfield.setEnabled(false);
        outliers_lower_bound_label.setEnabled(false);
        outliers_lower_bound_textfield.setEnabled(false);
        Globals.replaceOutliers = Globals.REPLACE_OUTLIERS_AUTO;
    }//GEN-LAST:event_outliers_auto_radiobuttonActionPerformed

    private void outliers_manually_radiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outliers_manually_radiobuttonActionPerformed
        outliers_tolerance_TextField.setEnabled(false);
        outliers_upper_bound_label.setEnabled(true);
        outliers_upper_bound_textfield.setEnabled(true);
        outliers_lower_bound_label.setEnabled(true);
        outliers_lower_bound_textfield.setEnabled(true);
        Globals.replaceOutliers = Globals.REPLACE_OUTLIERS_MANUALLY;
    }//GEN-LAST:event_outliers_manually_radiobuttonActionPerformed

    private void outliers_off_radiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outliers_off_radiobuttonActionPerformed
        outliers_tolerance_TextField.setEnabled(false);
        outliers_upper_bound_label.setEnabled(false);
        outliers_upper_bound_textfield.setEnabled(false);
        outliers_lower_bound_label.setEnabled(false);
        outliers_lower_bound_textfield.setEnabled(false);
        Globals.replaceOutliers = Globals.REPLACE_OUTLIERS_OFF;
    }//GEN-LAST:event_outliers_off_radiobuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FileOpenDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FileOpenDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FileOpenDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FileOpenDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FileOpenDialog dialog = new FileOpenDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox biasCheckbox;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton fileButton;
    private javax.swing.JLabel fileLabel;
    private javax.swing.JTextField fileTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JCheckBox normalizationCheckbox;
    private javax.swing.JButton okButton;
    private javax.swing.ButtonGroup outliersButtonGroup;
    private javax.swing.JLabel outliersToleranceLabel;
    private javax.swing.JRadioButton outliers_auto_radiobutton;
    private javax.swing.JLabel outliers_lower_bound_label;
    private javax.swing.JTextField outliers_lower_bound_textfield;
    private javax.swing.JRadioButton outliers_manually_radiobutton;
    private javax.swing.JRadioButton outliers_off_radiobutton;
    private javax.swing.JTextField outliers_tolerance_TextField;
    private javax.swing.JLabel outliers_upper_bound_label;
    private javax.swing.JTextField outliers_upper_bound_textfield;
    private javax.swing.JLabel replace_outliers_title;
    private javax.swing.JLabel samplingRateLabel;
    private javax.swing.JTextField samplingRateTextField;
    private javax.swing.JLabel zoomLabel1;
    private javax.swing.JLabel zoomLabel2;
    private javax.swing.JTextField zoomTextField;
    // End of variables declaration//GEN-END:variables
}
